### PR TITLE
Delete Meeting Minutes File

### PR DESCRIPTION
**Pull request by AbhB2303**
Deleting meeting minutes file because the information is included in the wiki section of the repository.

### CODE REVIEW

**Comment by eyadsw** [comment]
Having the information on the wiki is easier.

**Review by lailaalhalabi — APPROVED** [review]
Reviewed meeting minutes file

**Review by zeinebbenmami — APPROVED** [review]
Can be deleted

**Comment by hmarinov10** [comment]
File is unnecessary.

**Pull request merged**
